### ISSUE TITLE
Error: Reference does not exist

### ISSUE THREAD

**Issue by commandlinegirl** [author/action-rollback#10]
Hello, I'm using 

https://github.com/author/action-rollback/tree/1.0.3#workflow

```
      - name: Rollback release if unsuccessful
        if: ${{ cancelled() || failure() }}
        uses: author/action-rollback@stable
        with:
          release_id: ${{ steps.create-release.outputs.id }}
          delete_orphan_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and I'm getting the error:

![image](https://user-images.githubusercontent.com/2283292/108303640-21ebdb80-715b-11eb-86eb-37e25acb57ab.png)

If I delete `always_delete_tag` I still get the error `Error: Reference does not exist` but not the warning. I'm more concered with this error. Where can it be coming from? The release entry is indeed removed so the `release_id` works well.

**Comment by coreybutler** [comment]
The error means the Github reference does not exist. It throws this error when the release does not have a reference commit on Github (i.e. this error is triggered by the Github API).

The delete orphan tag feature was pulled out of stable... not because anything is wrong with it, but because other changes needed to be pulled out. You can try the master branch if you need that feature. I need to update the docs to explain this.

To use the master branch instead of stable:

```yaml
     - name: Rollback release if unsuccessful
        if: ${{ cancelled() || failure() }}
        uses: author/action-rollback@master
        with:
          release_id: ${{ steps.create-release.outputs.id }}
          delete_orphan_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
