### ISSUE TITLE
Stable branch is missing schema for delete_orphan_tag

### ISSUE THREAD

**Issue by Twipped** [author/action-rollback#12]
**Issue:**

Cannot use `delete_orphan_tag` when running from `@stable` because the schema for that option does not exist in the stable branch.

On master: https://github.com/author/action-rollback/blob/master/action.yml#L14-L16
On stable: https://github.com/author/action-rollback/blob/stable/action.yml#L7-L13

**How To Reproduce:**

```
      - name: Rollback Release if publish failed
        if: failure()
        uses: author/action-rollback@stable
        with:
          tag: ${{ matrix.package.tag }}
          delete_orphan_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Produces:

```
Warning: Unexpected input(s) 'delete_orphan_tag', valid inputs are ['release_id', 'tag']
Run author/action-rollback@stable
  with:
    tag: monorepo-sandbox-a-v1.1.0
    delete_orphan_tag: true
```
